name: Django CI

on:
  push:
    branches: [ "master", "ci/cd" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4


    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
  #      pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py test
