name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "${{ github.workspace }}/postman/collections/Mission Planner Scripts Postman.json" --integration-id "153006-${{ github.run_id }}"
          # Lint your API using Postman CLI
          postman api lint bf1d4fce-d19b-4bba-a4f6-9e0b6be96e47 --integration-id 153006
